config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/profile', to: 'pages#profile'

  get '/professors/pending', to: 'professors#index_pending'

  get '/courses/pending', to: 'courses#index_pending'
  
  get '/schools/:school_id/index_courses_professors', to: 'schools#index_courses_professors', as: 'school_courses_professors'

  get '/professor_course_evaluations/:id', to: 'professors#show_professor_course_evaluation', as: 'professor_course_evaluation'

  resources :universities, only: :index, shallow: true do
    resources :schools, only: :index do
      resources :courses do
        resources :course_evaluations, only: [:new, :create]
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
      resources :professors do
        resources :professor_evaluations
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations"}

  resources :notifications, only: [:index, :new, :create]

end

app/models/professor_evaluation.rb
class ProfessorEvaluation < ActiveRecord::Base
  belongs_to :user
  belongs_to :professor
end

app/controllers/professor_evaluations_controller.rb
class ProfessorEvaluationsController < ApplicationController
  before_action :set_professor_evaluation, only: [:show, :edit, :update, :destroy]

  # GET /professor_evaluations
  # GET /professor_evaluations.json
  def index
    @professor_evaluations = ProfessorEvaluation.all
  end

  # GET /professor_evaluations/1
  # GET /professor_evaluations/1.json
  def show
  end

  # GET /professor_evaluations/new
  def new
    @professor_id = params[:professor_id]
    professor = Professor.find(@professor_id)
    @course_list = professor.courses
    if @course_list.blank?
      redirect_to professor_path(id: params[:professor_id]), notice:  'Este profesor no tiene cursos asignados'
    else
      @professor_evaluation = ProfessorEvaluation.new
    end
  end

  # GET /professor_evaluations/1/edit
  def edit
  end

  # POST /course_evaluations
  # POST /course_evaluations.json
  def create
    professor_id = params[:professor_id].to_i
    @post_params = post_params_array
    evaluated_course_id = professor_evaluation_params[:course_id].to_i
    evaluation = ProfessorEvaluation.where(['user_id = ? and professor_id = ? and course_id = ?',current_user.id, professor_id, evaluated_course_id])
    if evaluation.blank?
      @professor_evaluation = ProfessorEvaluation.new(professor_evaluation_params)
      @professor_evaluation.user_id = current_user.id
      @professor_evaluation.professor_id = professor_id
      @professor_evaluation.overall_score = calculate_overall_score
      if @professor_evaluation.save
        modify_evaluated_professor
        modify_professor_course_evaluations
        redirect_to professor_path(id: professor_id), notice:  evaluation
      else
        render :new, notice:  'Hubo un error al evaluar'
      end
    else
      redirect_to professor_path(id: professor_id), notice:  'Ya habías evaluado a este profesor en dicho curso, solo se puede una vez!'
    end
  end

  # PATCH/PUT /professor_evaluations/1
  # PATCH/PUT /professor_evaluations/1.json
  def update
    respond_to do |format|
      if @professor_evaluation.update(professor_evaluation_params)
        format.html { redirect_to @professor_evaluation, notice: 'Professor evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor_evaluation }
      else
        format.html { render :edit }
        format.json { render json: @professor_evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professor_evaluations/1
  # DELETE /professor_evaluations/1.json
  def destroy
    @professor_evaluation.destroy
    respond_to do |format|
      format.html { redirect_to professor_evaluations_url, notice: 'Professor evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor_evaluation
      @professor_evaluation = ProfessorEvaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_evaluation_params
      params.require(:professor_evaluation).permit(:arrival_puntuality, :feedback_puntuality, :knowledge, :addresses_questions, :learning_interest, :difficulty, :clearness, :respectful, :course_id)
    end

    def modify_evaluated_professor
      professor = Professor.find(params[:professor_id])
      professor.evaluation_quantity = professor.evaluation_quantity + 1
      professor.overall_score = professor.overall_score +  @professor_evaluation.overall_score
      professor.overall_arrival_puntuality = professor.overall_arrival_puntuality + @professor_evaluation.arrival_puntuality
      professor.overall_feedback_puntuality = professor.overall_feedback_puntuality + @professor_evaluation.feedback_puntuality
      professor.overall_knowledge = professor.overall_knowledge + @professor_evaluation.knowledge
      professor.overall_addresses_questions = professor.overall_addresses_questions + @professor_evaluation.addresses_questions
      professor.overall_learning_interest = professor.overall_learning_interest + @professor_evaluation.learning_interest
      professor.overall_difficulty = professor.overall_difficulty + @professor_evaluation.difficulty
      professor.overall_clearness = professor.overall_clearness + @professor_evaluation.clearness
      professor.overall_respect = professor.overall_respect + @professor_evaluation.respectful
      professor.save
    end

    def modify_professor_course_evaluations
      professor_course_evaluation = ProfessorCourseEvaluation.where(['professor_id = ? and course_id = ?', params[:professor_id].to_i, @professor_evaluation.course_id]).limit(1).first
      professor_course_evaluation.evaluation_quantity = professor_course_evaluation.evaluation_quantity + 1
      professor_course_evaluation.overall_score = professor_course_evaluation.overall_score +  @professor_evaluation.overall_score
      professor_course_evaluation.overall_arrival_puntuality = professor_course_evaluation.overall_arrival_puntuality + @professor_evaluation.arrival_puntuality
      professor_course_evaluation.overall_feedback_puntuality = professor_course_evaluation.overall_feedback_puntuality + @professor_evaluation.feedback_puntuality
      professor_course_evaluation.overall_knowledge = professor_course_evaluation.overall_knowledge + @professor_evaluation.knowledge
      professor_course_evaluation.overall_addresses_question = professor_course_evaluation.overall_addresses_question + @professor_evaluation.addresses_questions
      professor_course_evaluation.overall_learning_interest = professor_course_evaluation.overall_learning_interest + @professor_evaluation.learning_interest
      professor_course_evaluation.overall_difficulty = professor_course_evaluation.overall_difficulty + @professor_evaluation.difficulty
      professor_course_evaluation.overall_clearness = professor_course_evaluation.overall_clearness + @professor_evaluation.clearness
      professor_course_evaluation.overall_respect = professor_course_evaluation.overall_respect + @professor_evaluation.respectful
      professor_course_evaluation.save
    end

    def calculate_overall_score
      res = 0
      @post_params.each do |val|
        res += val
      end
      res = (res - professor_evaluation_params[:difficulty].to_i - professor_evaluation_params[:course_id].to_i)/7.0
      return res
    end

    def post_params_array
      array = []
      professor_evaluation_params.each do |key, value|
        array.push(value.to_i)
      end
      return array
    end
end

app/helpers/professor_evaluations_helper.rb
module ProfessorEvaluationsHelper
end

app/views/professor_evaluations/_form.html.haml
.row
  .col-md-10.col-md-offset-1
    = form_for @professor_evaluation, url: professor_professor_evaluations_path, html: { class: "form form-horizontal professor_evaluation" } do |f|
      .row
        .col-md-4.col-md-offset-4
          .form-group
            = f.label :course_id, 'Seleccione el curso que desea evaluar', class: 'control-label'
            .controls.styled-select
              = f.select :course_id, options_for_select(@course_list.collect {|c| [ c.name, c.id ] }),{}, {}
            = error_span(@professor_evaluation[:overall_score])
      %hr
      .row
        .col-md-4.col-md-offset-1
          .form-group
            = f.label :arrival_puntuality, 'Puntual llegando a clases', class: 'control-label'
            .controls.styled-select
              = f.select :arrival_puntuality, options_for_select([['Nunca',1],['Casi nunca',2],['A veces',3],['Casi siempre',4],['Siempre',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])

          .form-group
            = f.label :feedback_puntuality, 'Puntual entregando evaluaciones revisadas', class: 'control-label'
            .controls.styled-select
              = f.select :feedback_puntuality, options_for_select([['Nunca',1],['Casi nunca',2],['A veces',3],['Casi siempre',4],['Siempre',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])

          .form-group
            = f.label :knowledge, 'Conocimiento y dominio de la materia', class: 'control-label'
            .controls.styled-select
              = f.select :knowledge, options_for_select([['Nada',1],['Poco',2],['Regular',3],['Mucho',4],['Dominio total',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])

          .form-group
            = f.label :addresses_questions, 'Atiende dudas de los estudiantes', class: 'control-label'
            .controls.styled-select
              = f.select :addresses_questions, options_for_select([['Nunca',1],['Casi nunca',2],['A veces',3],['Casi siempre',4],['Siempre',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])

        .col-md-4.col-md-offset-1
          .form-group
            = f.label :learning_interest, 'Se interesa por el aprendizaje del estudiante', class: 'control-label'
            .controls.styled-select
              = f.select :learning_interest, options_for_select([['Nada',1],['Muy poco',2],['Poco',3],['Regular',4],['Mucho',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])

          .form-group
            = f.label :difficulty, 'Dificultad de curso con este profesor', class: 'control-label'
            .controls.styled-select
              = f.select :difficulty, options_for_select([['Muy fácil',1],['Fácil',2],['Regular',3],['Difícil',4],['Muy difícil',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])

          .form-group
            = f.label :clearness, 'Las explicaciones son', class: 'control-label'
            .controls.styled-select
              = f.select :clearness, options_for_select([['No se le entiende nada',1],['Muy confusas',2],['Confusas',3],['Entendibles',4],['Excelentes',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])

          .form-group
            = f.label :respectful, 'Respetuoso (a)', class: 'control-label'
            .controls.styled-select
              = f.select :respectful, options_for_select([['Nunca',1],['Casi nunca',2],['A veces',3],['Casi siempre',4],['Siempre',5]]),{}, {:class => "selectpicker" }
            = error_span(@professor_evaluation[:overall_score])
      %hr
      .row
        = f.submit 'Añadir evaluación',class: 'btn btn-primary'
        = link_to t('.cancel', :default => t('Cancelar')), professor_path(id: @professor_id), :class => 'btn btn-default'
      %hr

app/views/professor_evaluations/edit.html.haml
- model_class = ProfessorEvaluation
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/professor_evaluations/index.html.haml
- model_class = ProfessorEvaluation
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:arrival_puntuality)
      %th= model_class.human_attribute_name(:feedback_puntuality)
      %th= model_class.human_attribute_name(:knowledge)
      %th= model_class.human_attribute_name(:addresses_questions)
      %th= model_class.human_attribute_name(:learning_interest)
      %th= model_class.human_attribute_name(:difficulty)
      %th= model_class.human_attribute_name(:clearness)
      %th= model_class.human_attribute_name(:respectful)
      %th= model_class.human_attribute_name(:course_name)
      %th= model_class.human_attribute_name(:overall_score)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:professor_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @professor_evaluations.each do |professor_evaluation|
      %tr
        %td= link_to professor_evaluation.id, professor_evaluation_path(professor_evaluation)
        %td= professor_evaluation.arrival_puntuality
        %td= professor_evaluation.feedback_puntuality
        %td= professor_evaluation.knowledge
        %td= professor_evaluation.addresses_questions
        %td= professor_evaluation.learning_interest
        %td= professor_evaluation.difficulty
        %td= professor_evaluation.clearness
        %td= professor_evaluation.respectful
        %td= professor_evaluation.course_name
        %td= professor_evaluation.overall_score
        %td= professor_evaluation.user_id
        %td= professor_evaluation.professor_id
        %td=l professor_evaluation.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_professor_evaluation_path(professor_evaluation), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), professor_evaluation_path(professor_evaluation), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_professor_evaluation_path, :class => 'btn btn-primary'

app/views/professor_evaluations/new.html.haml
- model_class = ProfessorEvaluation
.row
  .page-header
    %h1.title.text-center
      - p = Professor.find(params[:professor_id])
      = "Evaluación para #{p.name} #{p.last_name}"
  = render :partial => "form"

app/views/professor_evaluations/show.html.haml
- model_class = ProfessorEvaluation
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:arrival_puntuality) + ':'
  %br
  = @professor_evaluation.arrival_puntuality
%p
  %strong= model_class.human_attribute_name(:feedback_puntuality) + ':'
  %br
  = @professor_evaluation.feedback_puntuality
%p
  %strong= model_class.human_attribute_name(:knowledge) + ':'
  %br
  = @professor_evaluation.knowledge
%p
  %strong= model_class.human_attribute_name(:addresses_questions) + ':'
  %br
  = @professor_evaluation.addresses_questions
%p
  %strong= model_class.human_attribute_name(:learning_interest) + ':'
  %br
  = @professor_evaluation.learning_interest
%p
  %strong= model_class.human_attribute_name(:difficulty) + ':'
  %br
  = @professor_evaluation.difficulty
%p
  %strong= model_class.human_attribute_name(:clearness) + ':'
  %br
  = @professor_evaluation.clearness
%p
  %strong= model_class.human_attribute_name(:respectful) + ':'
  %br
  = @professor_evaluation.respectful
%p
  %strong= model_class.human_attribute_name(:course_name) + ':'
  %br
  = @professor_evaluation.course_name
%p
  %strong= model_class.human_attribute_name(:overall_score) + ':'
  %br
  = @professor_evaluation.overall_score
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @professor_evaluation.user_id
%p
  %strong= model_class.human_attribute_name(:professor_id) + ':'
  %br
  = @professor_evaluation.professor_id


= link_to t('.back', :default => t("helpers.links.back")), professor_evaluations_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_professor_evaluation_path(@professor_evaluation), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), professor_evaluation_path(@professor_evaluation), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'