config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/profile', to: 'pages#profile'

  get '/professors/pending', to: 'professors#index_pending'

  get '/courses/pending', to: 'courses#index_pending'
  
  get '/schools/:school_id/index_courses_professors', to: 'schools#index_courses_professors', as: 'school_courses_professors'

  get '/professor_course_evaluations/:id', to: 'professors#show_professor_course_evaluation', as: 'professor_course_evaluation'

  resources :universities, only: :index, shallow: true do
    resources :schools, only: :index do
      resources :courses do
        resources :course_evaluations, only: [:new, :create]
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
      resources :professors do
        resources :professor_evaluations
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations"}

  resources :notifications, only: [:index, :new, :create]

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  belongs_to :school
  has_and_belongs_to_many :courses
  has_many :professor_evaluations, :dependent => :destroy
  has_many :comments, as: :commentable, :dependent => :destroy
  has_many :professor_course_evaluations, :dependent => :destroy

  attr_accessor :professor_courses
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :index_pending]

  helper_method :calculate_overall

  # GET /professors
  # GET /professors.json
  def index
    school = School.find(params[:school_id])
    @professors = school.professors.order("overall_score DESC")
    render layout: false
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @professor = Professor.find(params[:id])
    @professor_courses = @professor.courses.where(state: 'accepted')
    @eq = @professor.evaluation_quantity
  end

  # GET /professors/new
  def new

    @school_id = params[:school_id]
    @professor = Professor.new
    @courses = School.find(@school_id).courses.where(state: 'accepted')
  end

  # GET /professors/1/edit
  def edit
    @school_id = @professor.school_id
  end

  def destroy
    @professor.destroy
    flash[:notice] = 'Se ha rechazado y eliminado el profesor!'
    redirect_to profile_path, status: 303
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new
    @professor.name = professor_params[:name]
    @professor.last_name = professor_params[:last_name]
    @professor.overall_score = 0;
    @professor.school_id = params[:school_id]
    @professor.creator_id = current_user.id

    respond_to do |format|
      if @professor.save
        add_selected_courses
        format.html { redirect_to school_courses_professors_path, notice: 'El profesor fue creado, enviaremos una notificación para que sepas si fue aceptado!' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: school_professors_path.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_professor_course_evaluation
    @professor_course_evaluation = ProfessorCourseEvaluation.find(params[:id])
    @eq = @professor_course_evaluation.evaluation_quantity
    professor = Professor.find(@professor_course_evaluation.professor_id)
    @professor_name = "#{professor.name} #{professor.last_name}"
    course = Course.find(@professor_course_evaluation.course_id)
    @course_name = course.name
  end

  def calculate_overall(overall_parameter, evaluation_quantity)
    if evaluation_quantity > 0
      res = (overall_parameter + 0.0) / evaluation_quantity
    else
      res = 0
    end
    return res.round(1)
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    @professor.state = 'accepted'
    @professor.save
    flash[:notice] = 'Se ha aceptado el profesor!'
    redirect_to profile_path, status: 303
  end

  def index_pending
    @professors = Professor.where(state: 'pending').order("created_at DESC")
    render layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name, :last_name, :professor_courses => [])
    end

    def add_selected_courses
      professor_courses = professor_params[:professor_courses]
      professor_courses.each do |c|
        id = c.to_i
        if id != 0
          @professor.courses << Course.find(id)
          insert_professor_course_evaluation(@professor.id, id)
        end
      end
    end

    def insert_professor_course_evaluation(professor_id, course_id)
      professor_course_evaluation = ProfessorCourseEvaluation.new
      professor_course_evaluation.professor_id = professor_id
      professor_course_evaluation.course_id = course_id
      professor_course_evaluation.save
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for @professor, url: school_professors_path(school_id: @school_id), html: { class: "form form-horizontal professor" } do |f|
      .form-group
        = f.label :name, 'Nombre del profesor', class: 'control-label'
        .controls
          = f.text_field :name, class: 'form-control', required: true
        = error_span(@professor[:name])
      .form-group
        = f.label :last_name, 'Apellido del profesor', class: 'control-label'
        .controls
          = f.text_field :last_name, class: 'form-control', required: true
        = error_span(@professor[:last_name])
      .form-group
        = f.label :professor_courses, 'Seleccione los cursos que imparte el profesor', class: 'control-label'
        .controls
          = f.select :professor_courses, options_for_select(@courses.collect {|c| [ c.name, c.id ] }),{}, {:multiple => true, :style => "width:100%;" }
        = error_span(@professor[:overall_score])
      %hr
      = f.submit 'Agregar profesor',class: 'btn btn-primary'
      = link_to t('.cancel', :default => t('Cancelar')), school_courses_professors_path, :class => 'btn btn-default'
      %hr

app/views/professors/edit.html.haml
- model_class = Professor
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/professors/index.html.haml
= render partial: "partials/alerts", flash: flash
- model_class = Professor
.page-header

  = link_to new_school_professor_path, :class => 'eval-button add-button' do
    %i.fa.fa-plus-circle
      Agregar profesor

  #sorts-professors.button-group
    %button.button-professors.button.is-checked{"data-sort-by" => "original-order"} Orden Original
    %button.button-professors.button{"data-sort-by" => "name"} Nombre

  %hr
  .row
    .col-md-10.col-md-offset-1
      .isotope-professors
        - @professors.each do |professor|
          - if professor.state.eql? "accepted"
            = link_to professor_path(id: professor.id) do
              .element-item
                %svg
                  %line.top{:x1 => "0", :x2 => "900", :y1 => "0", :y2 => "0"}
                  %line.left{:x1 => "0", :x2 => "0", :y1 => "460", :y2 => "-920"}
                  %line.bottom{:x1 => "300", :x2 => "-600", :y1 => "460", :y2 => "460"}
                  %line.right{:x1 => "300", :x2 => "300", :y1 => "0", :y2 => "1380"}
                %h3.name= professor.name + ' ' + professor.last_name
                %p.label Cantidad de evaluaciones
                %p.quantity= professor.evaluation_quantity
  %hr
%script{:src => "/assets/professors.js" }

app/views/professors/index_pending.html.haml
- @professors.each do |professor|
  .row.item-box
    .col-md-8
      %p.float-right
      %h3= "Profesor: #{professor.name} #{professor.last_name}"
      %p= "Universidad: #{professor.school.university.name} (id = #{professor.school.university.id})"
      %br
      %p= "Escuela: #{professor.school.name} (id = #{professor.school.id})"
    .col-md-4
      .buttons-container.pull-right.clear
        = link_to '', :class => 'margin-right-10 accept-button', userId: "#{professor.creator_id}", resourceId: "#{professor.id}" , resource: "professors",remote: true do
          %i.fa.fa-check-circle-o>
            Aceptar
        = link_to '', :class => 'margin-left-10 reject-button', userId: "#{professor.creator_id}", resourceId: "#{professor.id}" , resource: "professors", remote: true do
          %i.fa.fa-ban>
            Rechazar

app/views/professors/new.html.haml
- model_class = Professor
.row
  .page-header
    %h1.text-center.title
      Nuevo profesor
  = render :partial => "form"

app/views/professors/show.html.haml
- model_class = Professor
.page-header
  
  %h1.text-center.title
    = @professor.name + ' ' + @professor.last_name
  = link_to new_professor_professor_evaluation_path(professor_id: @professor.id), :class => 'eval-button add-button' do
    %i.fa.fa-pencil-square-o
      Evaluar profesor

.row
  .col-md-12
    .col-md-6
      %table.table.table-striped
        %thead
          %tr
            %th Criterio de evaluacion
            %th.text-center Promedio
        %tbody
          %tr
            %td Calificación general
            %td.text-center= calculate_overall(@professor.overall_score, @eq)
          %tr
            %td Puntual llegando a clases temprano
            %td.text-center= calculate_overall(@professor.overall_arrival_puntuality, @eq)
          %tr
            %td Puntual entregando evaluaciones revisadas
            %td.text-center= calculate_overall(@professor.overall_feedback_puntuality, @eq)
          %tr
            %td Conocimiento y dominio de la materia
            %td.text-center= calculate_overall(@professor.overall_knowledge, @eq)
          %tr
            %td Atiende dudas de los estudiantes
            %td.text-center= calculate_overall(@professor.overall_addresses_questions, @eq)
          %tr
            %td Se intereza por el aprendizaje del estudiante
            %td.text-center= calculate_overall(@professor.overall_learning_interest, @eq)
          %tr
            %td Dificultad del curso con este profesor
            %td.text-center= calculate_overall(@professor.overall_difficulty, @eq)
          %tr
            %td Claridad de las explicaciones
            %td.text-center= calculate_overall(@professor.overall_clearness, @eq)
          %tr
            %td Respeto hacia los estudiantes
            %td.text-center= calculate_overall(@professor.overall_respect, @eq)
      %hr
    .col-md-6
      .prof-list
        %h3 Evaluado en los cursos:
        %br
  
        .row
          .col-md-10.col-md-offset-1
            #list8
              %ul
                - @professor_courses.each do |course|
                  %li.text-center
                    - eval = ProfessorCourseEvaluation.where(['professor_id = ? and course_id = ?',@professor.id,course.id]).limit(1).first
                    = link_to professor_course_evaluation_path(id: eval.id) do
                      = "#{course.name} (#{eval.evaluation_quantity})"
        %hr
  .row
    / Comment section
    .col-md-10.col-md-offset-1.comments-column
      %section#comment-section
        %h4.text-center Comentarios
        #comments
      %button.show-comments-button{:action => "show", :value => "#{@professor.id}", :resource => 'professors'}
        Mostrar Comentarios
        %i.fa.fa-comments
  %hr
  
= link_to 'Atras', school_courses_professors_path(school_id: @professor.school_id), :class => 'btn btn-default'
%hr

app/views/professors/show_professor_course_evaluation.html.haml
.row
  .col-md-8.col-md-offset-2
    %hr
    %h1.text-center.title
      Profesor: 
      = @professor_name
    %h1.text-center.title
      Curso: 
      = @course_name
    %hr

    %table.table.table-striped
      %thead
        %tr
          %th Criterio de evaluacion
          %th.text-center Promedio
      %tbody
        %tr
          %td Calificación general
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_score, @eq)
        %tr
          %td Puntual llegando a clases
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_arrival_puntuality, @eq)
        %tr
          %td Puntual entregando evaluaciones revisadas
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_feedback_puntuality, @eq)
        %tr
          %td Conocimiento y dominio de la materia
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_knowledge, @eq)
        %tr
          %td Atiende dudas de los estudiantes
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_addresses_question, @eq)
        %tr
          %td Se interesa por el aprendizaje del estudiante
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_learning_interest, @eq)
        %tr
          %td Dificultad del curso con este profesor
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_difficulty, @eq)
        %tr
          %td Claridad de las explicaciones
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_clearness, @eq)
        %tr
          %td Respeto hacia los estudiantes
          %td.text-center= calculate_overall(@professor_course_evaluation.overall_respect, @eq)
    %hr