config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/profile', to: 'pages#profile'

  get '/professors/pending', to: 'professors#index_pending'

  get '/courses/pending', to: 'courses#index_pending'
  
  get '/schools/:school_id/index_courses_professors', to: 'schools#index_courses_professors', as: 'school_courses_professors'

  get '/professor_course_evaluations/:id', to: 'professors#show_professor_course_evaluation', as: 'professor_course_evaluation'

  resources :universities, only: :index, shallow: true do
    resources :schools, only: :index do
      resources :courses do
        resources :course_evaluations, only: [:new, :create]
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
      resources :professors do
        resources :professor_evaluations
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations"}

  resources :notifications, only: [:index, :new, :create]

end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :university
  has_many :courses, :dependent => :destroy
  has_many :professors, :dependent => :destroy
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  respond_to :json
  respond_to :html

  def index
    university = University.find(params[:university_id])
    @schools = university.schools
  end

  def index_courses_professors
    @school_id = params[:school_id]
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/index.html.haml
- model_class = School

.page-header
  %h1.text-center
    %i.fa.fa-book Escuelas
  %hr

  #sorts.button-group
    %button.button.is-checked{"data-sort-by" => "original-order"} Orden Original
    %button.button{"data-sort-by" => "name"} Ordenar por Nombre

  %hr
  .row
    .col-md-10.col-md-offset-1
      .isotope
        - @schools.each do |school|
          %a{:href => school_courses_professors_path(school_id: school.id)}
            .element-item
              %svg
                %line.top{:x1 => "0", :x2 => "900", :y1 => "0", :y2 => "0"}
                %line.left{:x1 => "0", :x2 => "0", :y1 => "460", :y2 => "-920"}
                %line.bottom{:x1 => "300", :x2 => "-600", :y1 => "460", :y2 => "460"}
                %line.right{:x1 => "300", :x2 => "300", :y1 => "0", :y2 => "1380"}
              %h3.name= school.name

= link_to 'Atras', root_path, :class => 'btn btn-default'
%hr

%script{:src => "/assets/schools.js" }

app/views/schools/index_angular.html.haml
.page-header
  %h1.text-center
    %i.fa.fa-book Escuelas
  %hr

  #sorts.button-group
    %button.button.is-checked{"data-sort-by" => "original-order"} Orden Original
    %button.button{"data-sort-by" => "name"} Ordenar por Nombre

  %hr
  .row
    .col-md-10.col-md-offset-1{"ng-app" => "UEval", "ng-controller" => "MainController"}
      .isotope
        - url_escaped_href = school_courses_professors_path('{{ s.id}}')
        - my_href = URI::unescape(url_escaped_href)
        = link_to my_href, {"ng-repeat" => "s in schools"} do
          .element-item
            %svg
              %line.top{:x1 => "0", :x2 => "900", :y1 => "0", :y2 => "0"}
              %line.left{:x1 => "0", :x2 => "0", :y1 => "460", :y2 => "-920"}
              %line.bottom{:x1 => "300", :x2 => "-600", :y1 => "460", :y2 => "460"}
              %line.right{:x1 => "300", :x2 => "300", :y1 => "0", :y2 => "1380"}
            %h3.name
              {{s.name}}
  %hr

%script{:src => "/assets/schools.js" }

app/views/schools/index_courses_professors.html.haml
#school-id{:schoolId => @school_id}
.row
  .col-md-10.col-md-offset-1
    %div{:role => "tabpanel", class: 'horizontal-tabs'}
      %ul.nav.nav-tabs{:role => "tablist"}
        %li.active.school-tab{:role => "presentation", resource: 'courses'}
          %a{"aria-controls" => "course", "data-toggle" => "tab", :href => "#courses", :role => "tab"} Cursos
        %li.school-tab{:role => "presentation", resource: 'professors'}
          %a{"aria-controls" => "professor", "data-toggle" => "tab", :href => "#professors", :role => "tab"} Profesores

      .tab-content
        #courses.tab-pane.active{:role => "tabpanel"} No hay cursos en esta escuela
        #professors.tab-pane{:role => "tabpanel"} No hay profesores en esta escuela
  
    = link_to 'Atras', university_schools_path(university_id: School.find(@school_id).university_id), :class => 'btn btn-default'
    %hr

%script{:src => "/assets/school_tabs.js" }