config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/profile', to: 'pages#profile'

  get '/professors/pending', to: 'professors#index_pending'

  get '/courses/pending', to: 'courses#index_pending'
  
  get '/schools/:school_id/index_courses_professors', to: 'schools#index_courses_professors', as: 'school_courses_professors'

  get '/professor_course_evaluations/:id', to: 'professors#show_professor_course_evaluation', as: 'professor_course_evaluation'

  resources :universities, only: :index, shallow: true do
    resources :schools, only: :index do
      resources :courses do
        resources :course_evaluations, only: [:new, :create]
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
      resources :professors do
        resources :professor_evaluations
        resources :comments, only: [:index, :new, :create, :destroy, :update]
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :sessions => "users/sessions", :registrations => "users/registrations"}

  resources :notifications, only: [:index, :new, :create]

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :index_pending]

  # GET /courses
  # GET /courses.json
  def index
    school = School.find(params[:school_id])
    @courses = school.courses.order("evaluation_quantity DESC")
    render layout: false
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    if(@course.evaluation_quantity > 0)
      @difficulty_average = ((@course.overall_difficulty+0.0) / @course.evaluation_quantity).round(1)
    else
      @difficulty_average = 0
    end
    @course_professors = @course.professors.where(state: 'accepted')
  end

  # GET /courses/new
  def new
    @course = Course.new
    @school_id = params[:school_id]
  end

  # GET /courses/1/edit
  def edit
    @school_id = @course.school_id
  end

  def destroy
    @course.destroy
    flash[:notice] = 'Se ha rechazado y eliminado el curso!'
    redirect_to profile_path, status: 303
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    @course.school_id = params[:school_id]
    @course.creator_id = current_user.id
    respond_to do |format|
      if @course.save
        format.html { redirect_to school_courses_professors_path, notice: 'El curso fue creado con éxito, se enviará una notificación cuando sea validado!' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: school_courses_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    @course.state = 'accepted'
    @course.save
    flash[:notice] = 'Se ha aceptado el profesor!'
    redirect_to profile_path, status: 303
  end

  def index_pending
    @courses = Course.where(state: 'pending')
    render layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.haml
= form_for @course, url: school_courses_path(school_id: @school_id), html: { class: "form form-horizontal course" } do |f|
  .form-group
    = f.label :name, 'Nombre del curso',class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@course[:name])
  = f.submit 'Agregar curso',class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("Cancelar")), school_courses_professors_path, :class => 'btn btn-default'

app/views/courses/index.html.haml
= render partial: "partials/alerts", flash: flash
- model_class = Course
.page-header

  = link_to new_school_course_path, :class => 'eval-button add-button' do
    %i.fa.fa-plus-circle
      Agregar curso

  #sorts-courses.button-group
    %button.button-courses.button.is-checked{"data-sort-by" => "original-order"} Orden Original
    %button.button-courses.button{"data-sort-by" => "name"} Nombre

  %hr
  .row
    .col-md-10.col-md-offset-1
      .isotope-courses
        - @courses.each do |course|
          - if course.state.eql? "accepted"
            = link_to course_path(id: course.id) do
              .element-item
                %svg
                  %line.top{:x1 => "0", :x2 => "900", :y1 => "0", :y2 => "0"}
                  %line.left{:x1 => "0", :x2 => "0", :y1 => "460", :y2 => "-920"}
                  %line.bottom{:x1 => "300", :x2 => "-600", :y1 => "460", :y2 => "460"}
                  %line.right{:x1 => "300", :x2 => "300", :y1 => "0", :y2 => "1380"}
                %h3.name= course.name
                %p.label Dificultad:
                - evalQuantity = course.evaluation_quantity
                - if evalQuantity > 0
                  - average = (course.overall_difficulty + 0.0)/evalQuantity
                -else
                  - average = 0
                %p.quantity= average
  %hr
%script{:src => "/assets/courses.js" }

app/views/courses/index_pending.html.haml
- @courses.each do |course|
  .row.item-box{resource: 'courses'}
    .col-md-8
      %p.float-right
      %h3= "Curso: #{course.name}"
      %p= "Universidad: #{course.school.university.name} - id = #{course.school.university.id}"
      %br
      %p= "Escuela: #{course.school.name} (id = #{course.school.id})"
    .col-md-4
      .buttons-container.pull-right.clear
        = link_to '', :class => 'accept-button margin-right-10', userId: "#{course.creator_id}", resourceId: "#{course.id}" , resource: "courses",remote: true do
          %i.fa.fa-check-circle-o>
            Aceptar
        = link_to '', :class => 'reject-button margin-left-10', userId: "#{course.creator_id}", resourceId: "#{course.id}" , resource: "courses", remote: true do
          %i.fa.fa-ban>
            Rechazar

app/views/courses/new.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => ['Nuevo curso'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courses/show.html.haml
.row
  .col-md-10.col-md-offset-1
    .page-header
      %h1.text-center.title= @course.name

  .row
    .col-md-10.col-md-offset-1
      = link_to new_course_course_evaluation_path(course_id: @course.id), :class => 'eval-button add-button' do
        %i.fa.fa-pencil-square-o
          Calificar dificultad
      %div.clear
      %hr
      .row
        .col-md-12
          .col-md-6
            %p.diff-label Dificultad promedio del curso:
            %p.diff-num= "(#{@difficulty_average})"
            %br
          .col-md-6
            .prof-list
              %h3 Lista de profesores
              %br
            #list8
              %ul
                - @course_professors.each do |professor|
                  %li.text-center
                    = link_to professor_path(id: professor.id) do
                      = professor.name + ' ' + professor.last_name
      %hr
      %section#comment-section
        %h4.text-center Comentarios
        #comments
      %button.show-comments-button{:action => "show", :value => "#{@course.id}", :resource => 'courses'}
        Mostrar Comentarios
        %i.fa.fa-comments
      %hr
      
= link_to 'Atras', school_courses_professors_path(school_id: @course.school_id), :class => 'btn btn-default'
%hr